"""Make User email optional

Revision ID: 05c14b5e27ab
Revises: 16b42ecdc7a2
Create Date: 2024-09-29 19:45:12.717789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05c14b5e27ab'
down_revision: Union[str, None] = '16b42ecdc7a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'email',
               existing_type=sa.TEXT(),
               nullable=True)
    op.create_index(op.f('ix_user_auth_method'), 'user', ['auth_method'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_auth_method'), table_name='user')
    op.alter_column('user', 'email',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
