"""Add source_file to File model

Revision ID: 0d0800088b4a
Revises: bda54b7325a8
Create Date: 2024-09-20 11:19:58.611116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d0800088b4a'
down_revision: Union[str, None] = 'bda54b7325a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('source_file_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True))
    op.create_foreign_key(None, 'file', 'file', ['source_file_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'file', type_='foreignkey')
    op.drop_column('file', 'source_file_id')
    # ### end Alembic commands ###
