"""Add Storage Provider to Folder model

Revision ID: 49974ebaed96
Revises: b489c6196eba
Create Date: 2025-12-10 15:56:23.379711

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "49974ebaed96"
down_revision: Union[str, None] = "b489c6196eba"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("folder", sa.Column("storage_provider", sa.UnicodeText(), nullable=True))
    op.create_index(
        op.f("ix_folder_storage_provider"), "folder", ["storage_provider"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_folder_storage_provider"), table_name="folder")
    op.drop_column("folder", "storage_provider")
    # ### end Alembic commands ###
