"""Add FileChat models

Revision ID: 807fb2e99394
Revises: 8139bf3ba1ca
Create Date: 2025-05-04 10:15:55.290216

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "807fb2e99394"
down_revision: Union[str, None] = "8139bf3ba1ca"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "filechat",
        sa.Column("title", sa.UnicodeText(), nullable=True),
        sa.Column("system_instructions", sa.UnicodeText(), nullable=False),
        sa.Column("uuid", sa.UUID(), nullable=False),
        sa.Column("incognito", sa.Boolean(), nullable=False),
        sa.Column("user_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("file_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("purged_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_purged", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["file_id"],
            ["file.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_filechat_incognito"), "filechat", ["incognito"], unique=False)
    op.create_index(op.f("ix_filechat_title"), "filechat", ["title"], unique=False)
    op.create_index(op.f("ix_filechat_uuid"), "filechat", ["uuid"], unique=False)
    op.create_table(
        "filechatmessage",
        sa.Column("request_prompt", sa.UnicodeText(), nullable=False),
        sa.Column("response_text", sa.UnicodeText(), nullable=False),
        sa.Column("uuid", sa.UUID(), nullable=False),
        sa.Column("runtime", sa.Float(), nullable=True),
        sa.Column("llm_model_provider", sa.UnicodeText(), nullable=True),
        sa.Column("llm_model_name", sa.UnicodeText(), nullable=True),
        sa.Column("llm_model_config", sa.UnicodeText(), nullable=True),
        sa.Column(
            "file_chat_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("purged_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_purged", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["file_chat_id"],
            ["filechat.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_filechatmessage_runtime"), "filechatmessage", ["runtime"], unique=False
    )
    op.create_index(op.f("ix_filechatmessage_uuid"), "filechatmessage", ["uuid"], unique=False)
    op.create_table(
        "filechatsummary",
        sa.Column("summary", sa.UnicodeText(), nullable=False),
        sa.Column("uuid", sa.UUID(), nullable=False),
        sa.Column("is_shared", sa.Boolean(), nullable=False),
        sa.Column("runtime", sa.Float(), nullable=True),
        sa.Column("status_short", sa.UnicodeText(), nullable=True),
        sa.Column("status_detail", sa.UnicodeText(), nullable=True),
        sa.Column("status_progress", sa.UnicodeText(), nullable=True),
        sa.Column("llm_model_prompt", sa.UnicodeText(), nullable=True),
        sa.Column("llm_model_provider", sa.UnicodeText(), nullable=True),
        sa.Column("llm_model_name", sa.UnicodeText(), nullable=True),
        sa.Column("llm_model_config", sa.UnicodeText(), nullable=True),
        sa.Column(
            "file_chat_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("purged_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_purged", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["file_chat_id"],
            ["filechat.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_filechatsummary_is_shared"), "filechatsummary", ["is_shared"], unique=False
    )
    op.create_index(
        op.f("ix_filechatsummary_runtime"), "filechatsummary", ["runtime"], unique=False
    )
    op.create_index(
        op.f("ix_filechatsummary_status_short"), "filechatsummary", ["status_short"], unique=False
    )
    op.create_index(op.f("ix_filechatsummary_uuid"), "filechatsummary", ["uuid"], unique=False)
    op.create_table(
        "filechatmessagefeedback",
        sa.Column(
            "file_chat_message_id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=False,
        ),
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("purged_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_purged", sa.Boolean(), nullable=False),
        sa.Column("upvote", sa.Boolean(), nullable=False),
        sa.Column("downvote", sa.Boolean(), nullable=False),
        sa.Column("feedback_text", sa.UnicodeText(), nullable=True),
        sa.Column("user_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True),
        sa.ForeignKeyConstraint(
            ["file_chat_message_id"],
            ["filechatmessage.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("filechatmessagefeedback")
    op.drop_index(op.f("ix_filechatsummary_uuid"), table_name="filechatsummary")
    op.drop_index(op.f("ix_filechatsummary_status_short"), table_name="filechatsummary")
    op.drop_index(op.f("ix_filechatsummary_runtime"), table_name="filechatsummary")
    op.drop_index(op.f("ix_filechatsummary_is_shared"), table_name="filechatsummary")
    op.drop_table("filechatsummary")
    op.drop_index(op.f("ix_filechatmessage_uuid"), table_name="filechatmessage")
    op.drop_index(op.f("ix_filechatmessage_runtime"), table_name="filechatmessage")
    op.drop_table("filechatmessage")
    op.drop_index(op.f("ix_filechat_uuid"), table_name="filechat")
    op.drop_index(op.f("ix_filechat_title"), table_name="filechat")
    op.drop_index(op.f("ix_filechat_incognito"), table_name="filechat")
    op.drop_table("filechat")
    # ### end Alembic commands ###
