"""Add purged fields

Revision ID: 8139bf3ba1ca
Revises: d2fa65588b7c
Create Date: 2025-03-28 13:59:54.595256

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8139bf3ba1ca"
down_revision: Union[str, None] = "d2fa65588b7c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("file", sa.Column("purged_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column(
        "file",
        sa.Column("is_purged", sa.Boolean(), nullable=False, server_default=sa.text("false")),
    )
    op.add_column(
        "fileattribute", sa.Column("purged_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "fileattribute",
        sa.Column("is_purged", sa.Boolean(), nullable=False, server_default=sa.text("false")),
    )
    op.add_column("filereport", sa.Column("purged_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column(
        "filereport",
        sa.Column("is_purged", sa.Boolean(), nullable=False, server_default=sa.text("false")),
    )
    op.add_column("filesummary", sa.Column("purged_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column(
        "filesummary",
        sa.Column("is_purged", sa.Boolean(), nullable=False, server_default=sa.text("false")),
    )
    op.add_column(
        "filesummaryfeedback", sa.Column("purged_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "filesummaryfeedback",
        sa.Column("is_purged", sa.Boolean(), nullable=False, server_default=sa.text("false")),
    )
    op.add_column("folder", sa.Column("purged_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column(
        "folder",
        sa.Column("is_purged", sa.Boolean(), nullable=False, server_default=sa.text("false")),
    )
    op.add_column(
        "folderattribute", sa.Column("purged_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "folderattribute",
        sa.Column("is_purged", sa.Boolean(), nullable=False, server_default=sa.text("false")),
    )
    op.add_column(
        "foldersummary", sa.Column("purged_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "foldersummary",
        sa.Column("is_purged", sa.Boolean(), nullable=False, server_default=sa.text("false")),
    )
    op.add_column("group", sa.Column("purged_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column(
        "group",
        sa.Column("is_purged", sa.Boolean(), nullable=False, server_default=sa.text("false")),
    )
    op.add_column("grouprole", sa.Column("purged_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column(
        "grouprole",
        sa.Column("is_purged", sa.Boolean(), nullable=False, server_default=sa.text("false")),
    )
    op.add_column("task", sa.Column("purged_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column(
        "task",
        sa.Column("is_purged", sa.Boolean(), nullable=False, server_default=sa.text("false")),
    )
    op.add_column("taskreport", sa.Column("purged_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column(
        "taskreport",
        sa.Column("is_purged", sa.Boolean(), nullable=False, server_default=sa.text("false")),
    )
    op.add_column("user", sa.Column("purged_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column(
        "user",
        sa.Column("is_purged", sa.Boolean(), nullable=False, server_default=sa.text("false")),
    )
    op.add_column("userapikey", sa.Column("purged_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column(
        "userapikey",
        sa.Column("is_purged", sa.Boolean(), nullable=False, server_default=sa.text("false")),
    )
    op.add_column("userrole", sa.Column("purged_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column(
        "userrole",
        sa.Column("is_purged", sa.Boolean(), nullable=False, server_default=sa.text("false")),
    )
    op.add_column("workflow", sa.Column("purged_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column(
        "workflow",
        sa.Column("is_purged", sa.Boolean(), nullable=False, server_default=sa.text("false")),
    )
    op.add_column(
        "workflowtemplate", sa.Column("purged_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "workflowtemplate",
        sa.Column("is_purged", sa.Boolean(), nullable=False, server_default=sa.text("false")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("workflowtemplate", "is_purged")
    op.drop_column("workflowtemplate", "purged_at")
    op.drop_column("workflow", "is_purged")
    op.drop_column("workflow", "purged_at")
    op.drop_column("userrole", "is_purged")
    op.drop_column("userrole", "purged_at")
    op.drop_column("userapikey", "is_purged")
    op.drop_column("userapikey", "purged_at")
    op.drop_column("user", "is_purged")
    op.drop_column("user", "purged_at")
    op.drop_column("taskreport", "is_purged")
    op.drop_column("taskreport", "purged_at")
    op.drop_column("task", "is_purged")
    op.drop_column("task", "purged_at")
    op.drop_column("grouprole", "is_purged")
    op.drop_column("grouprole", "purged_at")
    op.drop_column("group", "is_purged")
    op.drop_column("group", "purged_at")
    op.drop_column("foldersummary", "is_purged")
    op.drop_column("foldersummary", "purged_at")
    op.drop_column("folderattribute", "is_purged")
    op.drop_column("folderattribute", "purged_at")
    op.drop_column("folder", "is_purged")
    op.drop_column("folder", "purged_at")
    op.drop_column("filesummaryfeedback", "is_purged")
    op.drop_column("filesummaryfeedback", "purged_at")
    op.drop_column("filesummary", "is_purged")
    op.drop_column("filesummary", "purged_at")
    op.drop_column("filereport", "is_purged")
    op.drop_column("filereport", "purged_at")
    op.drop_column("fileattribute", "is_purged")
    op.drop_column("fileattribute", "purged_at")
    op.drop_column("file", "is_purged")
    op.drop_column("file", "purged_at")
    # ### end Alembic commands ###
