"""Add Storage Provider to File model

Revision ID: b489c6196eba
Revises: c92a24f59c0d
Create Date: 2025-10-21 10:49:30.862361

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b489c6196eba"
down_revision: Union[str, None] = "c92a24f59c0d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "file",
        sa.Column("storage_provider", sa.UnicodeText(), server_default="default", nullable=False),
    )
    op.add_column("file", sa.Column("storage_key", sa.UnicodeText(), nullable=True))
    op.create_index(op.f("ix_file_storage_key"), "file", ["storage_key"], unique=False)
    op.create_index(op.f("ix_file_storage_provider"), "file", ["storage_provider"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_file_storage_provider"), table_name="file")
    op.drop_index(op.f("ix_file_storage_key"), table_name="file")
    op.drop_column("file", "storage_key")
    op.drop_column("file", "storage_provider")
    # ### end Alembic commands ###
