"""Add original_path to File model

Revision ID: bda54b7325a8
Revises: 056d4d155b41
Create Date: 2024-09-20 10:53:38.550481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bda54b7325a8'
down_revision: Union[str, None] = '056d4d155b41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('original_path', sa.UnicodeText(), nullable=True))
    op.create_index(op.f('ix_file_original_path'), 'file', ['original_path'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_file_original_path'), table_name='file')
    op.drop_column('file', 'original_path')
    # ### end Alembic commands ###
