"""Add Storage Provider to File model

Revision ID: be54a5bf4f18
Revises: 807fb2e99394
Create Date: 2025-08-03 08:29:56.773643

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "be54a5bf4f18"
down_revision: Union[str, None] = "807fb2e99394"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "file",
        sa.Column("storage_provider", sa.UnicodeText(), server_default="default", nullable=False),
    )
    op.add_column("file", sa.Column("storage_key", sa.UnicodeText(), nullable=True))
    op.create_index(op.f("ix_file_storage_key"), "file", ["storage_key"], unique=False)
    op.create_index(op.f("ix_file_storage_provider"), "file", ["storage_provider"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_file_storage_provider"), table_name="file")
    op.drop_index(op.f("ix_file_storage_key"), table_name="file")
    op.drop_column("file", "storage_key")
    op.drop_column("file", "storage_provider")
    # ### end Alembic commands ###
