"""Add WorkflowTemplate relationship to Workflow

Revision ID: c92a24f59c0d
Revises: 807fb2e99394
Create Date: 2025-09-26 11:19:04.000451

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c92a24f59c0d"
down_revision: Union[str, None] = "807fb2e99394"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic ###
    op.add_column(
        "workflow",
        sa.Column(
            "template_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True
        ),
    )
    op.create_foreign_key(None, "workflow", "workflowtemplate", ["template_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic ###
    op.drop_constraint(None, "workflow", type_="foreignkey")
    op.drop_column("workflow", "template_id")
    # ### end Alembic commands ###
