"""Add TaskReport model

Revision ID: d2fa65588b7c
Revises: b7d67e6bb29e
Create Date: 2025-03-05 00:10:06.426644

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d2fa65588b7c"
down_revision: Union[str, None] = "b7d67e6bb29e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "taskreport",
        sa.Column("summary", sa.UnicodeText(), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("markdown", sa.UnicodeText(), nullable=False),
        sa.Column(
            "task_id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=True,
        ),
        sa.Column(
            "id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["task.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_taskreport_priority"), "taskreport", ["priority"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_taskreport_priority"), table_name="taskreport")
    op.drop_table("taskreport")
    # ### end Alembic commands ###
