"""Add new API keys model

Revision ID: d7409cc1bb27
Revises: 09f3a28f92cd
Create Date: 2024-09-28 11:34:27.655810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7409cc1bb27'
down_revision: Union[str, None] = '09f3a28f92cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('userapikey',
    sa.Column('display_name', sa.UnicodeText(), nullable=False),
    sa.Column('description', sa.UnicodeText(), nullable=True),
    sa.Column('token_jti', sa.UnicodeText(), nullable=False),
    sa.Column('token_exp', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_userapikey_display_name'), 'userapikey', ['display_name'], unique=False)
    op.create_index(op.f('ix_userapikey_token_jti'), 'userapikey', ['token_jti'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_userapikey_token_jti'), table_name='userapikey')
    op.drop_index(op.f('ix_userapikey_display_name'), table_name='userapikey')
    op.drop_table('userapikey')
    # ### end Alembic commands ###
